"use client";

import Image from "next/image";
import { FormEvent, useEffect, useState } from "react";

type Weekend = { id: string; year: number; month: string; days: string; dates: string; cafe: string; endsAt: string };
type Shift = { id: string; time: string };
type ConstructionDay = { date: string; weekday: string; endsAt: string; shifts: Shift[] };
type Signup = { id: string; weekend_id: string; day: string; name: string; created_at: string; event_type: string; role: string };
type SignupTarget = { eventType: "weekend" | "construction-week"; eventId: string; slot: string; title: string; role?: string };

const SIGNAL_URL = "https://www.regen406.de";
const roles = ["Verpflegung", "Lead", "Helfer:in"] as const;
const weekends: Weekend[] = [
  { id: "oct-2026", year: 2026, month: "Oktober", days: "17.–18.", dates: "17.–18. Oktober 2026", cafe: "So. 18.10. · Baustellencafé", endsAt: "2026-10-18T20:00:00+02:00" },
  { id: "nov-2026", year: 2026, month: "November", days: "14.–15.", dates: "14.–15. November 2026", cafe: "Sa. 14.11. · Baustellencafé", endsAt: "2026-11-15T20:00:00+01:00" },
  { id: "dec-2026", year: 2026, month: "Dezember", days: "12.–13.", dates: "12.–13. Dezember 2026", cafe: "Sa. 12.12. · Baustellencafé", endsAt: "2026-12-13T20:00:00+01:00" },
  { id: "jan-2027", year: 2027, month: "Januar", days: "09.–10.", dates: "09.–10. Januar 2027", cafe: "Sa. 09.01. · Baustellencafé", endsAt: "2027-01-10T20:00:00+01:00" },
  { id: "feb-2027", year: 2027, month: "Februar", days: "06.–07.", dates: "06.–07. Februar 2027", cafe: "Sa. 06.02. · Baustellencafé", endsAt: "2027-02-07T20:00:00+01:00" },
  { id: "mar-2027", year: 2027, month: "März", days: "06.–07.", dates: "06.–07. März 2027", cafe: "Sa. 06.03. · Baustellencafé", endsAt: "2027-03-07T20:00:00+01:00" },
];
const constructionDays: ConstructionDay[] = [
  { date: "09. Oktober", weekday: "Freitag", endsAt: "2026-10-09T20:00:00+02:00", shifts: [{ id: "fri-09-evening", time: "16–20 Uhr" }] },
  { date: "10. Oktober", weekday: "Samstag", endsAt: "2026-10-10T20:00:00+02:00", shifts: [{ id: "sat-10-morning", time: "10–15 Uhr" }, { id: "sat-10-evening", time: "15–20 Uhr" }] },
  { date: "11. Oktober", weekday: "Sonntag", endsAt: "2026-10-11T19:00:00+02:00", shifts: [{ id: "sun-11-morning", time: "10–15 Uhr" }, { id: "sun-11-evening", time: "15–19 Uhr" }] },
  { date: "14. Oktober", weekday: "Mittwoch", endsAt: "2026-10-14T20:00:00+02:00", shifts: [{ id: "wed-14-morning", time: "10–15 Uhr" }, { id: "wed-14-evening", time: "16–20 Uhr" }] },
  { date: "15. Oktober", weekday: "Donnerstag", endsAt: "2026-10-15T20:00:00+02:00", shifts: [{ id: "thu-15-morning", time: "10–15 Uhr" }, { id: "thu-15-evening", time: "16–20 Uhr" }] },
  { date: "16. Oktober", weekday: "Freitag", endsAt: "2026-10-16T20:00:00+02:00", shifts: [{ id: "fri-16-morning", time: "10–15 Uhr" }, { id: "fri-16-evening", time: "16–20 Uhr" }] },
  { date: "17. Oktober", weekday: "Samstag", endsAt: "2026-10-17T20:00:00+02:00", shifts: [{ id: "sat-17-morning", time: "10–15 Uhr" }, { id: "sat-17-evening", time: "15–20 Uhr" }] },
  { date: "18. Oktober", weekday: "Sonntag", endsAt: "2026-10-18T19:00:00+02:00", shifts: [{ id: "sun-18-morning", time: "10–15 Uhr" }, { id: "sun-18-evening", time: "15–19 Uhr" }] },
];
const CONSTRUCTION_WEEK_END = "2026-10-18T20:00:00+02:00";
const THANK_YOU_DAYS = 5;

function SignupNames({ people, myIds, cancellationIds, onCancel }: { people: Signup[]; myIds: string[]; cancellationIds: string[]; onCancel: (signup: Signup) => void }) {
  if (!people.length) return <p className="signup-empty">Noch niemand eingetragen</p>;
  return <ul className="signup-names">{people.map((person) => <li key={person.id} className={myIds.includes(person.id) ? "is-me" : ""}>{person.name}{myIds.includes(person.id) && (cancellationIds.includes(person.id) ? <small>Abmeldung angefragt</small> : <button type="button" onClick={() => onCancel(person)}>Abmelden</button>)}</li>)}</ul>;
}
function WeekendPeople({ people, myIds, cancellationIds, onCancel }: { people: Signup[]; myIds: string[]; cancellationIds: string[]; onCancel: (signup: Signup) => void }) {
  return <div className="people"><p className="help-counter">{people.length} {people.length === 1 ? "helfende Person" : "helfende Menschen"}</p>{(["Samstag", "Sonntag"] as const).map((day) => <div className="people-day" key={day}><span>{day}</span><SignupNames people={people.filter((person) => person.day === day)} myIds={myIds} cancellationIds={cancellationIds} onCancel={onCancel} /></div>)}</div>;
}

export default function Home() {
  const [signups, setSignups] = useState<Signup[]>([]); const [name, setName] = useState(""); const [comment, setComment] = useState(""); const [weekendDay, setWeekendDay] = useState("Samstag"); const [target, setTarget] = useState<SignupTarget | null>(null); const [myIds, setMyIds] = useState<string[]>([]); const [status, setStatus] = useState<"idle" | "saving" | "error">("idle"); const [cancellation, setCancellation] = useState<Signup | null>(null); const [cancellationIds, setCancellationIds] = useState<string[]>([]); const [cancellationStatus, setCancellationStatus] = useState<"idle" | "saving" | "error">("idle"); const [completedTarget, setCompletedTarget] = useState<SignupTarget | null>(null); const [now, setNow] = useState<Date | null>(null); const [openConstructionDay, setOpenConstructionDay] = useState<string | null>(null);
  useEffect(() => { fetch("/api/signups").then((response) => response.json()).then((data) => setSignups(data.signups ?? [])).catch(() => setStatus("error")); const saved = window.localStorage.getItem("regen406-my-signups"); if (saved) setMyIds(JSON.parse(saved)); const cancellationSaved = window.localStorage.getItem("regen406-cancellation-requests"); if (cancellationSaved) setCancellationIds(JSON.parse(cancellationSaved)); }, []);
  useEffect(() => { const previewDate = new URLSearchParams(window.location.search).get("previewDate"); const parsedPreview = previewDate && /^\d{4}-\d{2}-\d{2}$/.test(previewDate) ? new Date(`${previewDate}T12:00:00+02:00`) : null; setNow(parsedPreview && !Number.isNaN(parsedPreview.getTime()) ? parsedPreview : new Date()); }, []);
  useEffect(() => { if (!now) return; setOpenConstructionDay(constructionDays.find((day) => new Date(day.endsAt) > now)?.date ?? null); }, [now]);
  function openSignup(nextTarget: SignupTarget) { setTarget(nextTarget); setWeekendDay("Samstag"); setStatus("idle"); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!target) return; setStatus("saving"); const day = target.eventType === "weekend" ? weekendDay : target.slot; try { const response = await fetch("/api/signups", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ weekendId: target.eventId, day, name, comment, eventType: target.eventType, role: target.role }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSignups((current) => [...current, data.signup]); const updated = [...myIds, data.signup.id]; setMyIds(updated); window.localStorage.setItem("regen406-my-signups", JSON.stringify(updated)); setName(""); setComment(""); setCompletedTarget(target); setTarget(null); setStatus("idle"); } catch { setStatus("error"); } }
  async function requestCancellation() { if (!cancellation) return; setCancellationStatus("saving"); try { const response = await fetch("/api/cancellations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ signupId: cancellation.id }) }); if (!response.ok) throw new Error(); const updated = [...cancellationIds, cancellation.id]; setCancellationIds(updated); window.localStorage.setItem("regen406-cancellation-requests", JSON.stringify(updated)); setCancellationStatus("idle"); setCancellation(null); } catch { setCancellationStatus("error"); } }
  const effectiveNow = now ?? new Date("2026-01-01T12:00:00+01:00");
  const constructionWeekVisible = effectiveNow < new Date(CONSTRUCTION_WEEK_END);
  function weekendState(weekend: Weekend) { const end = new Date(weekend.endsAt); if (effectiveNow < end) return "open"; return effectiveNow.getTime() < end.getTime() + THANK_YOU_DAYS * 86400000 ? "thanks" : "hidden"; }
  function weekendCards(year: number) { return weekends.filter((weekend) => weekend.year === year && weekendState(weekend) !== "hidden").map((weekend) => { const people = signups.filter((signup) => signup.weekend_id === weekend.id && signup.event_type !== "construction-week"); const isSignedUp = myIds.some((id) => people.some((person) => person.id === id)); const isThanks = weekendState(weekend) === "thanks"; return <article className={`weekend-card ${isThanks ? "is-thanks" : ""}`} key={weekend.id}><div className="date"><span>{weekend.days}</span><strong>{weekend.month}</strong></div><div className="card-content"><p className="cafe-note">{weekend.cafe}</p><WeekendPeople people={people} myIds={myIds} cancellationIds={cancellationIds} onCancel={setCancellation} />{isThanks ? <p className="event-finished">Danke an alle, die mitgeholfen haben!</p> : <button type="button" onClick={() => openSignup({ eventType: "weekend", eventId: weekend.id, slot: "", title: weekend.dates })}>{isSignedUp ? "Weiteren Tag eintragen" : "Ich helfe mit"}</button>}</div></article>; }); }

  return <main>
    <header className="site-header"><a href="https://www.regen406.de" aria-label="Zur REGEN406 Website"><Image src="/regen406-logo.png" width={104} height={130} alt="REGEN406" priority /></a><a className="back-link" href="https://www.regen406.de">← zur REGEN406 Website</a></header>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">MITBAUEN BEI REGEN406</p><h1>Gemeinsam<br /><em>anpacken.</em></h1><p>Ob große Baustellen-Woche oder einzelnes Wochenende: Jede helfende Hand zählt. Du brauchst keine Vorerfahrung – nur Lust aufs Mitmachen. Auch wenn du nur kurz Zeit hast: Trag dich bitte ein – das hilft uns bei Essen, Werkzeug und Ausrüstung.</p><div className="hero-actions"><a className="signal-intro" href={SIGNAL_URL} target="_blank" rel="noreferrer">Infos via Signal <span>↗</span></a><a href="#baustellenwoche">Baustellen-Woche <span>↓</span></a><a href="#termine">Baustellen-Wochenenden <span>↓</span></a></div></div></section>
    {constructionWeekVisible && <section className="construction-week" id="baustellenwoche"><div className="construction-week-copy"><div><p className="eyebrow">09.–18. OKTOBER 2026</p><h2>REGEN406<br />Baustellen-Woche</h2></div><div className="construction-week-intro"><p>Wir wollen gemeinsam die Sandarbeiten im Dachboden stemmen. Wenn jeden Tag genug mitmachen, können wir die Arbeiten selbst schaffen und unserem Projekt rund 20.000 € sparen.</p><p>Für Essen, Getränke und einen gemeinsamen Ausklang am Lagerfeuer ist gesorgt. Also: Freund:innen schnappen, Schicht aussuchen und mitbauen!</p><p>Wähle einen Tag, eine Zeit und deine Rolle. Du kannst dich für beliebig viele Schichten eintragen.</p></div></div><div className="shift-plan">{constructionDays.filter((day) => new Date(day.endsAt) > effectiveNow).map((day) => { const [dateNumber, month] = day.date.split(" "); const isOpen = openConstructionDay === day.date; const helperCount = day.shifts.flatMap((shift) => signups.filter((signup) => signup.event_type === "construction-week" && signup.day === shift.id && signup.role === "Helfer:in")).length; return <section className={`construction-day ${isOpen ? "is-open" : "is-collapsed"}`} key={day.date}><button type="button" className="mobile-card-toggle" onClick={() => setOpenConstructionDay(isOpen ? null : day.date)} aria-expanded={isOpen}><header><span>{dateNumber}</span><strong>{month}</strong><small>{day.weekday} · {helperCount} {helperCount === 1 ? "helfende Person" : "helfende Menschen"}</small></header></button><div className="construction-shifts">{day.date === "18. Oktober" && <p className="construction-cafe">Baustellencafé · 15–17 Uhr</p>}{day.shifts.map((shift) => <div className="construction-shift" key={shift.id}><h5>{shift.time}</h5><div className="role-grid">{roles.map((role) => { const people = signups.filter((signup) => signup.event_type === "construction-week" && signup.day === shift.id && signup.role === role); return <article className="role-card" key={role}><p className="role-name">{role}</p>{role === "Helfer:in" && <p className="help-counter">{people.length} {people.length === 1 ? "helfende Person" : "helfende Menschen"}</p>}<SignupNames people={people} myIds={myIds} cancellationIds={cancellationIds} onCancel={setCancellation} /><button type="button" onClick={() => openSignup({ eventType: "construction-week", eventId: "construction-week", slot: shift.id, title: `${day.weekday}, ${day.date} · ${shift.time}`, role })}>Eintragen</button></article>; })}</div></div>)}</div></section>; })}</div></section>}
    <section className="weekends" id="termine"><div className="section-heading"><h2>REGEN406<br />Baustellen-<br />Wochenenden</h2><p>An unseren Baustellen-Wochenenden bringen wir REGEN406 gemeinsam voran. Das Baustellencafé öffnet jeweils am angegebenen Tag von <strong>15–17 Uhr</strong> – für alle, die neugierig sind, die Baustelle anschauen und uns bei Getränken und Snacks kennenlernen wollen.</p></div>{weekendCards(2026).length > 0 && <><h3>2026</h3><div className="cards">{weekendCards(2026)}</div></>}{weekendCards(2027).length > 0 && <><h3 className="year-heading">2027</h3><div className="cards">{weekendCards(2027)}</div></>}</section>
    {target && <div className="modal-backdrop" role="presentation" onMouseDown={() => setTarget(null)}><section className="signup-modal" role="dialog" aria-modal="true" aria-labelledby="signup-title" onMouseDown={(event) => event.stopPropagation()}><button className="close" type="button" aria-label="Schließen" onClick={() => setTarget(null)}>×</button><p className="eyebrow">{target.title}</p><h2 id="signup-title">Super, dass du dabei bist!</h2><p>{target.eventType === "construction-week" ? <>Du hilfst als <strong>{target.role}</strong>.</> : "Trag deinen Namen ein – wir freuen uns auf dich."}</p><form onSubmit={submit}><label>Name<input required value={name} onChange={(event) => setName(event.target.value)} autoComplete="name" /></label><label>Kommentar <span className="optional">(optional)</span><textarea value={comment} onChange={(event) => setComment(event.target.value)} maxLength={500} rows={3} placeholder="Zum Beispiel: Ich komme etwas später." /></label>{target.eventType === "weekend" && <fieldset><legend>Wann kannst du helfen?</legend><div className="day-buttons">{["Samstag", "Sonntag"].map((option) => <button key={option} type="button" className={weekendDay === option ? "selected" : ""} onClick={() => setWeekendDay(option)}>{option}</button>)}</div></fieldset>}{status === "error" && <p className="error">Das hat leider nicht geklappt. Bitte versuch es gleich noch einmal.</p>}<button className="submit" type="submit" disabled={status === "saving"}>{status === "saving" ? "Wird eingetragen …" : "Verbindlich eintragen"}</button></form></section></div>}
    {completedTarget && <div className="modal-backdrop" role="presentation" onMouseDown={() => setCompletedTarget(null)}><section className="signup-modal success-modal" role="dialog" aria-modal="true" aria-labelledby="success-title" onMouseDown={(event) => event.stopPropagation()}><button className="close" type="button" aria-label="Schließen" onClick={() => setCompletedTarget(null)}>×</button><p className="eyebrow">ANMELDUNG GESPEICHERT</p><h2 id="success-title">Super, du bist dabei!</h2><p>Du bist für <strong>{completedTarget.title}</strong> eingetragen.</p><a className="signal-cta" href={SIGNAL_URL} target="_blank" rel="noreferrer">Signal-Gruppe beitreten <span>↗</span></a><p className="signal-note">Dort teilen wir aktuelle Infos zu Bau-Wochenenden und der Baustellen-Woche.</p></section></div>}
    {cancellation && <div className="modal-backdrop" role="presentation" onMouseDown={() => setCancellation(null)}><section className="signup-modal cancellation-modal" role="dialog" aria-modal="true" aria-labelledby="cancellation-title" onMouseDown={(event) => event.stopPropagation()}><button className="close" type="button" aria-label="Schließen" onClick={() => setCancellation(null)}>×</button><p className="eyebrow">ABMELDUNG ANFRAGEN</p><h2 id="cancellation-title">Kannst du doch nicht?</h2><p>Deine Abmeldung für <strong>{cancellation.name}</strong> wird an das REGEN406-Team geschickt. Die Anmeldung wird nicht automatisch gelöscht.</p>{cancellationStatus === "error" && <p className="error">Das hat leider nicht geklappt. Bitte versuch es gleich noch einmal.</p>}<button className="submit" type="button" onClick={requestCancellation} disabled={cancellationStatus === "saving"}>{cancellationStatus === "saving" ? "Wird gesendet …" : "Abmeldung verbindlich anfragen"}</button></section></div>}
    <footer><Image src="/regen406-logo.png" width={64} height={80} alt="REGEN406" /><div><p>Regensburger Straße 406 · 90480 Nürnberg</p><a href="mailto:hallo@regen406.de">hallo@regen406.de</a><a href="https://www.regen406.de/impressum">Impressum</a><a href="https://www.regen406.de/datenschutz">Datenschutz</a></div></footer>
  </main>;
}
